language: python
sudo: required
dist: xenial

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - texlive-latex-extra
      - python3
      - pandoc

  # # OS X
  # homebrew:
  #   update: true
  #   packages:
  #     - pandoc

# before_script:
#   - mkdir build
#   - cd build

script:
  - python3 src/build.py .
  
notifications:
  email:
    - diemmarkus@gmail.com
