language: python
sudo: required
dist: xenial

os:
  - linux

addons:
  apt:
    update: true
    packages:
      - texlive-latex-extra
      - python3
      - pandoc
      - lmodern # needed for md -> pdf
      - texlive-fonts-recommended

script:
  - python3 src/build.py .
  
notifications:
  email:
    - diemmarkus@gmail.com
